[package]
name = "preview"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
image = "0.25.6"
wild = "2.2.1"
rvc_shared = { path = "../rvc_shared" }
rayon = "1.10.0"
